version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/chattingApp 
    overwrite: yes 

permissions:
  - object: / 
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
AfterInstall:
  - location: scripts/execute.sh 
    timeout: 600