version: '3.8'
services:
  nestapp:
    image: changmin97/chatting-image:latest
    container_name: nestapp-blue
    restart: always
    ports:
      - '3002:3000'
    env_file:
      - ../envfiles/chatting.env
    networks:
      chatting-net:
        external: true
      # - chatting-net