name: Deploy NestJS Application
# main 브랜치로 push 혹은 pr이 날라와서 merge되면 workflow가 작동합니다.
# workflow_dispatch는 수동으로 workflow를 작동시키도록 할 수 있도록 합니다.
on:
  push:
    branches: [ CI_Test ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      S3_BUCKET_NAME: changmincodedeploy # S3 버킷 이름입니다.
      PROJECT_NAME: chattingApp # S3 버킷 내 폴더 이름입니다. 임의로 정하면 알아서 생성해줍니다.
      AWS_CODEDEPLOY_APPLICATION_NAME: chattingAppCodeDeploy # CodeDeploy 애플리케이션 이름입니다.
      AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME: chattingAppDG # CodeDeploy 배포 그룹 이름입니다.
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatting-image:latest

      # 해당 workflow가 레포지토리에 접근할 수 있도록 해줍니다.
      # 우리는 레포지토리의 소스를 빌드해야하기 때문에 이 액션을 사용해야합니다.
      - name: Checkout Repository
        uses: actions/checkout@v3
     
      # 16.18.1 버전의 NodeJS를 세팅해줍니다.
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.18.1
      
      # Dependency들을 설치합니다. yarn도 사용 가능합니다.
      - name: Install Dependencies
        run: npm install
        
      # NestJS Application을 빌드합니다.
      - name: Build a Nest Application
        run: npm run build
        shell: bash
      
      # 레포지토리를 압축시킵니다.
      # 다만 불필요한 node_module, coverage, src, test, readme, .git* 등의 파일은 제외시킵니다.
      - name: Make a zip file
        run: zip -r ./$GITHUB_SHA.zip . -x "node_modules/*" "coverage/*" "src/*" "test/*" "README.md" "*.git*"
        shell: bash
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 위에서 만든 zip 파일을 S3에 업로드 합니다.
      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      # CodeDeploy에게 deployment를 생성하도록 요청합니다.
      - name: Request Deployment
        run: aws deploy create-deployment --application-name $AWS_CODEDEPLOY_APPLICATION_NAME --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name $AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
