name: dev push
on:
  push:
    branches-ignore:
      - main

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Run Test
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

  Docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          script: |
            echo "Login to docker Hub"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatting-image:dev
  Deploy:
    needs: [Docker]
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            ls
            cd chatting
            ls
            node -v
            sudo git pull https://github.com/lecDev97/chatting.git ${{github.ref_name}}
            cat ./src/app.service.ts
            sudo npm install
            sudo npm run build
            sudo pm2 restart all
