name: CI on all dev branch
on:
  push:
    branches-ignore:
      - main

jobs:
  Test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Run Test
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

        
# *dev branch 에 push할 경우
# 1)test code

# *main branch에 push or pull Request할 경우
# 1)test code
# 2)pull image
# 3)run container -d -p option or docker-compose up -d
