name: SERVER distribute

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          script:
            cd /home/ubuntu/chatting
            sudo git pull
            sudo npm install
            # sudo npm run build
            pm2 reload all
