name: Node.js CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            node -v
            sudo git pull https://github.com/lecDev97/chatting.git main
            cat ./src/app.service.ts




      # cd chatting
      # sudo git pull https://github.com/lecDev97/chatting.git main
      # sudo cat ./src/app.service.ts
      # sudo npm install
      # sudo npm install --save-dev fork-ts-checker-webpack-plugin
      # sudo npm link webpack
      # sudo npm run build
      # pm2 reload all
      # - run: sudo -s
      # - run: git clone https://github.com/lecDev97/chatting.git
      # - run: cd chatting
      # - run: npm install
      # - run: npm install --save-dev fork-ts-checker-webpack-plugin
      # - run: npm link webpack
      # - run: cat ./src/app.service.ts
      # - run: npm run build
      # - run: pm2 kill
      # - run: pm2 start ./dist/main.js



      # --if-present 옵션은 npm 스크립트가 존재할 때만 실행시키라는 의미이다.
      # 만약 build 스크립트가 없는 경우, 오류 없이 지나간다.
      # - run: git clone https://github.com/lecDev97/chatting.git
      # - run: ls
      # - run: cd chatting
      # - run: ls
      # - run: npm install
      # - run: npm install --save-dev fork-ts-checker-webpack-plugin
      # - run: npm link webpack
      # - run: npm run build
      # - run: pm2 kill
      # - run: pm2 start dist/main.js



