name: main pull request
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test-Build-Deploy on main Branch
    runs-on: ubuntu-20.04
    steps:
      - name: Run Test
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

  Deploy:
    runs-on: ubuntu-20.04
    uses: appleboy/ssh-action@master
    steps:
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_SSH_ID }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script: |
          cd chatting
          sudo git pull https://github.com/lecDev97/chatting.git main
          cat ./src/app.service.ts
          sudo npm install
          sudo npm run build
          sudo pm2 restart all
