name: CI/CD on main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  Test:
    name: Test-Build-Deploy on main Branch
    runs-on: ubuntu-20.04
    steps:
      - name: Run Test
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm test


  Docker:
    name: Docker Login-Build-Push :dev
    needs: [Test]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          script: |
            echo "Login to docker Hub"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatting-image:latest


  Docker-Compose:
    needs: [Docker]
    runs-on: ubuntu-20.04
    steps:
      - name: Connection to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            sudo docker stop chatting-app
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/chatting-image:latest
            sudo docker run -d --name chatting-app -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/chatting-image:dev
            sudo docker ps -al 